### ISSUE TITLE
Error while running the script AttributeError: module 'asyncio' has no attribute 'create_task while running.

### ISSUE THREAD

**Issue by AshKumar06** [thewhiteh4t/FinalRecon#15]
The script generated this error while running ,AttributeError: module 'asyncio' has no attribute 'create_task while running. Just replaced create_task with asyncio.ensure_future and it executed without errors.

**Comment by thewhiteh4t** [comment]
@AshKumar06 looks like you are using some python version below `3.7` , `create_task` was added in python version `3.7` , upgrade and it will work, closing.
