### ISSUE TITLE
shows error even with dependency installed

### ISSUE THREAD

**Issue by 01010000-kumar** [thewhiteh4t/FinalRecon#21]
$sudo ./finalrecon.py
```

[+] Checking Dependencies...

[-] tldextract is not Installed!
[-] icmplib is not Installed! 

```
---------------------------------------------------------------------------------------------------------------------------------------------

$pip3 install tldextract icmplib
```

Requirement already satisfied: tldextract in /home/user/.local/lib/python3.8/site-packages (2.2.2)
Requirement already satisfied: icmplib in /home/user/.local/lib/python3.8/site-packages (1.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tldextract) (46.1.3)
Requirement already satisfied: requests-file>=1.4 in /usr/lib/python3/dist-packages (from tldextract) (1.5.1)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from tldextract) (2.9)
Requirement already satisfied: requests>=2.1.0 in /usr/lib/python3/dist-packages (from tldextract) (2.23.0)

```

**Comment by thewhiteh4t** [comment]
share output of `python3 --version` and try executing `python3 finalrecon.py`

**Comment by 01010000-kumar** [comment]
$python3 --version

```
Python 3.8.3
```
---------------------------------------------------------------------------------------------------------------------------------------------------

$sudo python3 finalrecon.py 

```

[+] Checking Dependencies...

[-] tldextract is not Installed!
[-] icmplib is not Installed!

[-] Please Execute pip3 install -r requirements.txt to Install Missing Packages

```

**Comment by thewhiteh4t** [comment]
hmmmmm strange, what is the output of `pip3 --version`

**Comment by thewhiteh4t** [comment]
another thing, did you execute `pip3 install -r requirements.txt` or `sudo pip3 install -r requirements.txt` ?

**Comment by 01010000-kumar** [comment]
> another thing, did you execute `pip3 install -r requirements.txt` or `sudo pip3 install -r requirements.txt` ?

with a sudo

**Comment by 01010000-kumar** [comment]
> another thing, did you execute `pip3 install -r requirements.txt` or `sudo pip3 install -r requirements.txt` ?

tried executing with a `sudo` works fine now

**Comment by thewhiteh4t** [comment]
@01010000-kumar cool, thanks, I will update the install instructions and include sudo in pip command
