### ISSUE TITLE
ERROR SHOWS UP DURING CRAWLING A TARGET

### ISSUE THREAD

**Issue by whiteorange007** [thewhiteh4t/FinalRecon#26]
When we use to crawl a target like the command finalrecon --crawl https://abc.com there shows up this error:
/FinalRecon/modules/crawler.py", line 387, in out
    data['module-Crawler'].update({'Title':soup.title.string})
AttributeError: 'NoneType' object has no attribute 'string'

This happens only with few targets,not all target shows this error.

**Comment by thewhiteh4t** [comment]
@whiteorange007 if its possible can you disclose one of the targets where you are facing this issue? that will help me in reproducing the  issue on my end, if you dont want to disclose here you can send me a message on telegram

**Comment by whiteorange007** [comment]
Here is the target:https://www.kolikkopelit.com/

**Comment by thewhiteh4t** [comment]
yes i have the same issue on my end, thanks I will fix it soon @whiteorange007

**Comment by whiteorange007** [comment]
ALL THE BEST

**Comment by thewhiteh4t** [comment]
@whiteorange007 please update to `v1.0.8` :)
