### ISSUE TITLE
Anyone can fix this?

### ISSUE THREAD

**Issue by Haryzez** [thewhiteh4t/FinalRecon#28]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f_9re_78/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f_9re_78/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-faxuxsh9
         cwd: /tmp/pip-install-f_9re_78/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-faxuxsh9/psycopg2.egg-info
    writing /tmp/pip-pip-egg-info-faxuxsh9/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-faxuxsh9/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-faxuxsh9/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-faxuxsh9/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by thewhiteh4t** [comment]
@Haryzez which operating system are you using?

**Comment by Haryzez** [comment]
> @Haryzez which operating system are you using?

Linux 4.4.0-18362-Microsoft x86_64

**Comment by thewhiteh4t** [comment]
@Haryzez WSL?

**Comment by Haryzez** [comment]
Yeah

**Comment by Haryzez** [comment]
> @Haryzez WSL?

yes

**Comment by thewhiteh4t** [comment]
@Haryzez the error provided you a solution if you read it : 
```
If you prefer to avoid building psycopg2 from source, please install the PyPI
'psycopg2-binary' package instead.
```
Just execute `pip3 install psycopg2-binary`

**Comment by Haryzez** [comment]
> @Haryzez the error provided you a solution if you read it :
> 
> ```
> If you prefer to avoid building psycopg2 from source, please install the PyPI
> 'psycopg2-binary' package instead.
> ```
> 
> Just execute `pip3 install psycopg2-binary`

thank for the help , i just use   pip install (package)
it work for me

**Comment by thewhiteh4t** [comment]
@Haryzez cool, closing.
