### ISSUE TITLE
Subdomain Enumeration Problem

### ISSUE THREAD

**Issue by cagriaslan** [thewhiteh4t/FinalRecon#32]
Hi,

First thank you for this great tool. While I was testing it, I saw that it returns IP addresses along with the subdomains. This is also reflected to total number of subdomains. I consider this as a bug but if there are any other motivations can you please elaborate?

Thanks

**Comment by thewhiteh4t** [comment]
thanks @cagriaslan for reaching out, this is a good point, adding it to to-do list

**Comment by thewhiteh4t** [comment]
@cagriaslan fixed in `v1.1.1` please update and test
