### ISSUE TITLE
Subdomain, Port Scan & Dirsearch

### ISSUE THREAD

**Issue by attacker34** [thewhiteh4t/FinalRecon#4]
Dear @thewhiteh4t 

its looking for a good but it need enhancements like

1. Subdomain Scan
2. Port Scan
3. Dirsearch 

Sincerely,

**Comment by thewhiteh4t** [comment]
Thanks, already working on these along with more features, it will be updated soon!

**Comment by thewhiteh4t** [comment]
@attacker34 please update to v1.0.2, all requests added!
