### ISSUE TITLE
"statusCode": 401, "message": "Access denied due to improperly formed hibp-api-key." }

### ISSUE THREAD

**Issue by pockets8603** [thewhiteh4t/FinalRecon#41]
Help

[+] API Key Found...

[+] Checking Breach status for aguilera.paul@gmail.com

[-] An Unknown Error Occurred
{ "statusCode": 401, "message": "Access denied due to improperly formed hibp-api-key." }

[+] Completed in 0.10766911506652832 seconds.
PS C:\Users\aguil\pwnedOrNot>

**Comment by thewhiteh4t** [comment]
@pockets8603 you have opened the issue in wrong repository. The repository for pwnedOrNot is here : https://github.com/thewhiteh4t/pwnedOrNot
