### ISSUE TITLE
Handle exception 

### ISSUE THREAD

**Issue by abuvanth** [thewhiteh4t/FinalRecon#45]
File "finalrecon.py", line 275, in <module>
    full_recon()
  File "finalrecon.py", line 207, in full_recon
    dnsrec(domain, output, data)
  File "/root/finalrecon/modules/dns.py", line 19, in dnsrec
    pkt = q.send('8.8.8.8', 53, tcp='UDP')
  File "/usr/lib/python3.8/site-packages/dnslib/dns.py", line 365, in send
    sock.connect((dest,port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by thewhiteh4t** [comment]
@abuvanth provide more info so that I can reproduce the error on my end

**Comment by abuvanth** [comment]
Just run the full can against a target

**Comment by sushantbhadauria** [comment]
@thewhiteh4t , Is this issue fixed ? I am able to run full scan

 
![Screenshot 2022-06-27 at 6 39 34 PM](https://user-images.githubusercontent.com/22721881/175949575-f23881c6-9a23-4877-bd2e-267f05323a61.png)

**Comment by thewhiteh4t** [comment]
@sushantbhadauria this issue was kind of rare, most people did not have it

**Comment by abuvanth** [comment]
working fine
