### ISSUE TITLE
Permission denied while starting finalrecon

### ISSUE THREAD

**Issue by rmrf-sl4sh** [thewhiteh4t/FinalRecon#46]
In tracelabs kali I get the following while trying to start finalrecon:

`zsh: permission denied: finalrecon`

not sure why, and trying with sudo doesn't recognize the command

**Comment by thewhiteh4t** [comment]
@jdqw210 i will test, thanks

**Comment by mini-bomba** [comment]
sounds like the file is missing execute permissions
try finding the file using `which finalrecon` and then give it execute permissions with `chmod +x`

**Comment by thewhiteh4t** [comment]
@jdqw210 so I tested and you can fix it by executing the following commands : 
```
sudo sed -i 's/FinalRecon/finalrecon/g' /usr/bin/finalrecon

sudo chmod +x /usr/bin/finalrecon
```

**Comment by jdqw210** [comment]
Thank you kindly
