### ISSUE TITLE
Error with the psycopg2-binary python library. 

### ISSUE THREAD

**Issue by daniloalbuqrque** [thewhiteh4t/FinalRecon#47]
I looked for someone whom had faced the same problem, but I didn't find. I also tried to install the application in either Fedora 34 and Kali LTS version, and I got the same error in both:

```
[+] Checking Dependencies...

[-] psycopg2-binary is not Installed!

[-] Please Execute pip3 install -r requirements.txt to Install Missing Packages
```
When I try to run the application I face the error above. I have the library already installed, the `pip` is at the latest version. I already have uninstalled it and then installed it again. I tried to uninstall python and to install it again as well. As a proof that I have this specific library installed and updated, when I run the `pip3 install -r requirements.txt` command, it returns:

**Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 8)) (2.9.3)**

Thank y'all!

**Comment by thewhiteh4t** [comment]
@daniloalbuqrque the path of the lib you mentioned is under /usr which suggests that you executed `sudo pip3 install` ? and you are running finalrecon without sudo ?

if you are running finalrecon without sudo, run pip3 install without sudo as well and check if you still get the error

**Comment by daniloalbuqrque** [comment]
I ran all the attempts mentioned above with and without sudo permissions, and I still get the same error.

**Comment by thewhiteh4t** [comment]
@daniloalbuqrque what is the output of `python3 -c 'import psycopg2'` ?

**Comment by daniloalbuqrque** [comment]
Actually, there is no output.

**Comment by thewhiteh4t** [comment]
@daniloalbuqrque blank output means import was successful, edit `requirements.txt` remove the line which contains `psycopg2-binary` and run finalrecon again

**Comment by thewhiteh4t** [comment]
weird, share `cat /etc/os-release` and `python3 -V`

**Comment by daniloalbuqrque** [comment]
```
➜  FinalRecon git:(master) ✗ cat /etc/os-release 
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.1"
VERSION_ID="2022.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
➜  FinalRecon git:(master) ✗ python -V
Python 2.7.18
```
FYI: I am using the Python3.9 version to run the finalrecon.py file.

**Comment by thewhiteh4t** [comment]
@daniloalbuqrque did you install finalrecon from apt ?

**Comment by daniloalbuqrque** [comment]
I tried both ways, from apt and then from git to test it through another way.

**Comment by thewhiteh4t** [comment]
@daniloalbuqrque thanks I will try to reproduce the issue

**Comment by thewhiteh4t** [comment]
@daniloalbuqrque i have setup kali 2022.1 , I did get the psycopg2-binary error same as you and after editing rrequirrements.txt file and running the tool I am not getting the errors you have...
![frr_test](https://user-images.githubusercontent.com/36354846/157076810-64522ff2-07c2-41dc-8217-11dcd61c6b5f.png)

**Comment by thewhiteh4t** [comment]
@daniloalbuqrque please try `pip3 show aiohttp`
![Screenshot 2022-03-08 001558](https://user-images.githubusercontent.com/36354846/157098108-01d09cf0-921c-4612-8426-36e5f103ed61.png)

**Comment by thewhiteh4t** [comment]
if the version is old, update and try finalrecon again

**Comment by daniloalbuqrque** [comment]
@thewhiteh4t, thank you! I got it now, it was that, the version for that package was in the `3.7.4`. I updated and it has been resolved. Thank you very much!

**Comment by thewhiteh4t** [comment]
great! @daniloalbuqrque I will probably remove the package checking soon

**Comment by daniloalbuqrque** [comment]
Ok then! I will close the issue. Thank you for your time!
