### ISSUE TITLE
Dependency checker does not recognise the psycopg2-binary package

### ISSUE THREAD

**Issue by mini-bomba** [thewhiteh4t/FinalRecon#48]
When trying to run this script from source, I encountered an issue where the dependency checker would complain about `psycopg2-binary` package not being installed, even though it definetly was installed.

I found that even though the package was named `psycopg2-binary`, the actual module was still called `psycopg2`.
This issue was most likely introduced by commit [`716f133b`](https://github.com/thewhiteh4t/FinalRecon/commit/716f133b899727efbb43de8ed8199d54b1bdbe2b).

**Comment by thewhiteh4t** [comment]
@mini-bomba refer to https://github.com/thewhiteh4t/FinalRecon/issues/47

**Comment by mini-bomba** [comment]
I think this should be fixed rather than having an undocumented workaround.
I can submit a pull request.

**Comment by thewhiteh4t** [comment]
@mini-bomba no worries I will push an update soon
