### ISSUE TITLE
Attention: Someone stole your work

### ISSUE THREAD

**Issue by Zelakolase** [thewhiteh4t/FinalRecon#50]
Hello there,
Someone has stole your source code and changed the name of the project. 

Link : https://github.com/motasemroot/MotasemRecon

**Comment by thewhiteh4t** [comment]
@Zelakolase thanks for reaching out, unfortunately according to MIT and other open source licenses they can do that, but they have still breached the license by not following terms of MIT license i.e. ```The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.```

**Comment by Zelakolase** [comment]
You can file a DMCA takedown notice, or taking proper legal actions as detailed below:

https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice

https://opensource.stackexchange.com/a/5122

https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy

**Comment by thewhiteh4t** [comment]
@Zelakolase thanks a lot, I will go through these links and will do something about this

**Comment by Zelakolase** [comment]
Hello Again, I'd like to make an update.
He deleted the license completely, as an attempt to preserve his repository from a takedown.
[Commit Link](https://github.com/motasemroot/MotasemRecon/commit/c4f36eca3ce773556d27c2abed0e946c0a8f9394)

**Comment by thewhiteh4t** [comment]
@Zelakolase the DMCA takedown request was successful, GitHub has removed the copied repo, thanks a lot!
