### ISSUE TITLE
Keeps crashing 

### ISSUE THREAD

**Issue by bretfeig** [thewhiteh4t/FinalRecon#51]
**Update***

This seems to be caused by installing via APT.  When I followed the Git Clone  / PIP3 Requirements, it worked fine. 

Hi -  Getting an error using just --webcrawl URL

Traceback (most recent call last):
  File "/usr/share/finalrecon/finalrecon.py", line 152, in fetch_meta
    gh_version = json_data['metadata']['version']
KeyError: 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/finalrecon/finalrecon.py", line 218, in <module>
    fetch_meta()
  File "/usr/share/finalrecon/finalrecon.py", line 163, in fetch_meta
    with open('metadata.json', 'r') as metadata:
FileNotFoundError: [Errno 2] No such file or directory: 'metadata.jso

Received the same error on Kali Linux WSL2 and then on my VM which is running the latest Parrot OS

**Comment by thewhiteh4t** [comment]
@bretfeig yes I am aware of this issue and for kali linux I have raised issue on their bug tracker, need to wait for kali devs to update the tool, meanwhile you can `git clone` latest and that should work

**Comment by thewhiteh4t** [comment]
https://bugs.kali.org/view.php?id=7696

**Comment by thewhiteh4t** [comment]
@bretfeig v1.1.3 update is now available in kali linux, please try updating and let me know if it works now
