### ISSUE TITLE
Modify results directory

### ISSUE THREAD

**Issue by kenseilabs** [thewhiteh4t/FinalRecon#55]
I couln't find how to redirect the results to another folder without still using de default one.

**Comment by thewhiteh4t** [comment]
@kenseilabs can you elaborate the issue ?

**Comment by BerenBoden** [comment]
> @kenseilabs can you elaborate the issue ?

I think they are talking about using the `-o` option for exporting to a file that is not the default export, at the moment it is exporting to this path:
/home/user/.local/share/finalrecon/dumps/fr_example.com_04-05-2023_21:21:31

However, I get an issue when using the `-o` option to try and export to a different directory:
Traceback (most recent call last):
  File "/home/user/FinalRecon/finalrecon.py", line 216, in <module>
    dnsrec(domain, output, data)
  File "/home/user/FinalRecon/modules/dns.py", line 72, in dnsrec
    export(output, data)
  File "/home/user/FinalRecon/modules/export.py", line 12, in export
    if output['export'] is True:
KeyError: 'export'
