### ISSUE TITLE
ZSH: Segmentation Fault on Kali 2022.3

### ISSUE THREAD

**Issue by s1nglethr3ad** [thewhiteh4t/FinalRecon#56]
sudo apt-get install finalrecon
python3 finalrecon.py --full 'https://mydomain.com'

Running finalrecon in zsh on Kali produces:
zsh:  segmentation fault python3 finalrecon.py --full 'https://mydomain.com'

Error occurs during enumeration of subdomains.

Running subdomains separately produces same error.
python3 finalrecon.py --sub 'https://mydomain.com'
zsh:  segmentation fault python3 finalrecon.py --sub 'https://mydomain.com'

Is there a way to remdiate?
Thank you!

**Comment by thewhiteh4t** [comment]
@s1nglethr3ad finalrecon version ?

**Comment by s1nglethr3ad** [comment]
@thewhiteh4t 
v1.1.3 from Kali repo.

**Comment by thewhiteh4t** [comment]
@s1nglethr3ad it looks like the upgrade request is not completed yet 
https://bugs.kali.org/view.php?id=7837
until its complete you can `git clone` to use v1.1.5

**Comment by s1nglethr3ad** [comment]
@thewhiteh4t 
sounds good, i'll give it a go.  thank you!
