### ISSUE TITLE
no api key detected while keys are added into keys.json (m1 mac)

### ISSUE THREAD

**Issue by puchkii** [thewhiteh4t/FinalRecon#58]
output below from the scan:
[!] Skipping VirusTotal : API key not found!
[!] Skipping Shodan : API key not found!

format of keys.json:
{
	"virustotal": "key",
	"shodan": "key"
}

**Comment by thewhiteh4t** [comment]
@puchkii looks like you are using an old version, also check the following path : `$HOME/.config/finalrecon/`

**Comment by puchkii** [comment]
i found the issue. so i used the finalrecon/conf/keys.json instead of .config/finalrecon/keys.json. thx for responding so quickly and keep up the good work!
