### ISSUE TITLE
Subdomain Enumeration error

### ISSUE THREAD

**Issue by lordzenox** [thewhiteh4t/FinalRecon#65]
I have issue in the subdomain enumeration. When I use the --sub switch the following error is showing: 
(kali㉿KALI)-[~]
└─$ finalrecon --sub http://tesla.com

 ______  __   __   __   ______   __                                                                                                                                   
/\  ___\/\ \ /\ "-.\ \ /\  __ \ /\ \                                                                                                                                  
\ \  __\\ \ \\ \ \-.  \\ \  __ \\ \ \____                                                                                                                             
 \ \_\   \ \_\\ \_\\"\_\\ \_\ \_\\ \_____\                                                                                                                            
  \/_/    \/_/ \/_/ \/_/ \/_/\/_/ \/_____/                                                                                                                            
 ______   ______   ______   ______   __   __                                                                                                                          
/\  == \ /\  ___\ /\  ___\ /\  __ \ /\ "-.\ \                                                                                                                         
\ \  __< \ \  __\ \ \ \____\ \ \/\ \\ \ \-.  \                                                                                                                        
 \ \_\ \_\\ \_____\\ \_____\\ \_____\\ \_\\"\_\                                                                                                                       
  \/_/ /_/ \/_____/ \/_____/ \/_____/ \/_/ \/_/                                                                                                                       

[>] Created By   : thewhiteh4t
 |---> Twitter   : https://twitter.com/thewhiteh4t
 |---> Community : https://twc1rcle.com/
[>] Version      : 1.1.6

[+] Target : http://tesla.com

[+] IP Address : 104.85.4.91

[!] Starting Sub-Domain Enumeration...

[!] Requesting AnubisDB
[!] Requesting ThreatMiner
[!] Requesting CertSpotter
[!] Requesting Wayback
[!] Requesting HackerTarget
[!] Requesting crt.sh
[+] CRT.sh found 331 subdomains!
Traceback (most recent call last):
  File "/usr/bin/finalrecon", line 234, in <module>
    subdomains(domain, tout, out_settings, data, conf_path)
  File "/usr/share/finalrecon/modules/subdom.py", line 54, in subdomains
    loop.run_until_complete(query(hostname, tout, conf_path))
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/finalrecon/modules/subdom.py", line 31, in query
    await asyncio.gather(
  File "/usr/share/finalrecon/modules/subdomain_modules/bevigil_subs.py", line 18, in bevigil
    json_load = loads(json_read)
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 1 (char 230) "

Please give me the solution of this problem.

**Comment by thewhiteh4t** [comment]
@lordzenox is this only happening with tesla domain or every domain ?

**Comment by thewhiteh4t** [comment]
@lordzenox ran a quick test in termux, I am not able to reproduce this error

![Screenshot_20231207-082226.png](https://github.com/thewhiteh4t/FinalRecon/assets/36354846/b2d0227a-723b-4d43-a93f-6f220ba53cb7)
