### ISSUE TITLE
Error with CAA (Certification Authority Authorization) DNS Record Type

### ISSUE THREAD

**Issue by AswinWhiteHat** [thewhiteh4t/FinalRecon#66]
**Description:**
I encountered an issue while using FinalRecon related to the handling of the CAA DNS record type. The tool raises a KeyError during the execution, and it seems to be related to the DNS library (`dnslib`) used by FinalRecon.

**Steps to Reproduce:**
1. Run FinalRecon with a specific domain.
2. Observe the error related to the CAA DNS record type.

**Expected Behavior:**
The tool should handle the CAA DNS record type without raising errors.

**Environment:**
- FinalRecon Version: [v1.1.6]
- Python Version: [Python 3.11.7]
- Operating System: [kail linux ]

**Additional Information:**
Include any additional information that might be relevant to the issue. For example, details about your environment, sample commands you used, or any error messages displayed.

**Screenshots or Error Output:**
Attach screenshots or copy-paste error output that may help in understanding the issue.
![Screenshot_2024-02-05_13_12_59](https://github.com/thewhiteh4t/FinalRecon/assets/122371769/0a23c6c7-1fa6-46f7-ae02-97cb72d9ba06)

**Comment by thewhiteh4t** [comment]
@ASWINSRIRAM2004-hub can you provide the target you were testing on? I want to reproduce this error on my end

**Comment by thewhiteh4t** [comment]
fixed in https://github.com/thewhiteh4t/FinalRecon/commit/0802bd2977c4f9558f0a2ecb0fc279d21f6752ca
