### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by richdear** [thewhiteh4t/FinalRecon#67]
Traceback (most recent call last):
  File "/opt/FinalRecon/finalrecon.py", line 183, in <module>
    parsed_url = extractor.extract_urllib(split_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TLDExtract' object has no attribute 'extract_urllib'

Runnig ubuntu 24.04 with python3.12

**Comment by thewhiteh4t** [comment]
@richdear update tldextract to latest version using pip
